//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPIMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recibo
    {
        public Recibo(NewRecibo newRecibo)
        {
            Monto = newRecibo.Monto;
            Fecha = DateTime.Now;
            Comentario = newRecibo.Comentario;
            Activo = true;
        }
        public void Update(NewRecibo newRecibo)
        {
            Monto = newRecibo.Monto;
            Fecha = DateTime.Now;
            Comentario = newRecibo.Comentario;
            Activo = true;
        }

        public Recibo()
        {
        }
        public int idRecibo { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Comentario { get; set; }
        public bool Activo { get; set; }
  
        public virtual Moneda Moneda { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
